spring:
  datasource:
    url: jdbc:mysql://mysql-service.chat-app.svc.cluster.local:3306/chat-app-database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka-service.chat-app.svc.cluster.local:9092

  data:
    redis:
      host: redis-service.chat-app.svc.cluster.local
      port: 6379

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
