spring:
  datasource:
    # Local K8s configuration
    # url: jdbc:mysql://mysql-service.chat-app.svc.cluster.local:3306/chat-app-database
    # AWS RDS configuration
    url: jdbc:mysql://chat-app-mysql.cod8o8ck2y1e.us-east-1.rds.amazonaws.com:3306/chatappdatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    # Local K8s configuration
    # bootstrap-servers: kafka-service.chat-app.svc.cluster.local:9092
    # AWS MSK configuration
    bootstrap-servers: b-1.chatappkafka.xo3j3c.c22.kafka.us-east-1.amazonaws.com:9094,b-2.chatappkafka.xo3j3c.c22.kafka.us-east-1.amazonaws.com:9094
    properties:
      security.protocol: SSL

  data:
    redis:
      # Local K8s configuration
      # host: redis-service.chat-app.svc.cluster.local
      # AWS ElastiCache configuration
      host: chat-app-redis.ybwh7f.0001.use1.cache.amazonaws.com
      port: 6379

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
