apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: chat-app
spec:
  type: ClusterIP
  selector:
    app: chat-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
