apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-config
  namespace: chat-app
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service.chat-app.svc.cluster.local:3306/chat-app-database"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service.chat-app.svc.cluster.local:9092"
  SPRING_DATA_REDIS_HOST: "redis-service.chat-app.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
