apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: chat-app
type: Opaque
stringData:
  DB_USERNAME: "chat-app-user"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_use-a-long-random-secret-at-least-256-bits"
